# docker compose up --build -d  で寝る前に起動
# docker logs -f Docker_BLFS     で進捗確認
# docker compose down           でコンテナ削除

services:
  linux:
    env_file: .env
    cpus: ${CPU_CORE}

    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}

    build:
      context: ${Dockerfile_DIR}
      dockerfile: ${Dockerfile}
      args:
        WS:          ${WS}
        ENTRY_DIR:   ${ENTRY_DIR}
        ENTRY_POINT: ${ENTRY_POINT}
        LANG:        ${LANG}

    volumes:
      - ${VOLUME}:/${WS}   # ホスト ./build → コンテナ内 /build

    privileged: true        # mount / chroot に必須
    pid: host               # カーネル操作に必要

    restart: no             # ビルド完了後に自動再起動しない

    stop_grace_period: 12h  # 長時間ビルドを途中で止めない

    environment:
      - LFS_VERSION=${LFS_VERSION}
      - LFS_ARCH=${LFS_ARCH}
      - LFS_TGT=${LFS_TGT}
      - LFS_MIRRORS=${LFS_MIRRORS}
      - GNU_MIRRORS=${GNU_MIRRORS}
      - GCC_INFRA_MIRRORS=${GCC_INFRA_MIRRORS}
      - DL_RETRIES=${DL_RETRIES:-3}
      - DL_TIMEOUT=${DL_TIMEOUT:-90}
      - CPU_CORE=${CPU_CORE}
      - WS=${WS}
      - TZ=${TIME_ZONE}
      - LOCALE=${LOCALE}
      - LANG=${LANG}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - CLI_URL_EXPAT=${CLI_URL_EXPAT}
      - CLI_URL_SUDO=${CLI_URL_SUDO}
      - CLI_URL_NANO=${CLI_URL_NANO}
      - CLI_URL_CURL=${CLI_URL_CURL}
      - CLI_URL_PCRE2=${CLI_URL_PCRE2}
      - CLI_URL_GIT=${CLI_URL_GIT}
      - CLI_URL_HTOP=${CLI_URL_HTOP}
      - CLI_URL_LIBEVENT=${CLI_URL_LIBEVENT}
      - CLI_URL_TMUX=${CLI_URL_TMUX}
      - CLI_URL_TREE=${CLI_URL_TREE}
      - CLI_URL_BASH_COMPLETION=${CLI_URL_BASH_COMPLETION}
      - CLI_URL_DBUS=${CLI_URL_DBUS}
      - CLI_URL_IPROUTE2=${CLI_URL_IPROUTE2}
      - CLI_URL_DHCPCD=${CLI_URL_DHCPCD}
      - CLI_URL_OPENSSH=${CLI_URL_OPENSSH}
      - CLI_URL_LIBGPG_ERROR=${CLI_URL_LIBGPG_ERROR}
      - CLI_URL_LIBGCRYPT=${CLI_URL_LIBGCRYPT}
      - CLI_URL_GROFF=${CLI_URL_GROFF}
      - CLI_URL_GRUB=${CLI_URL_GRUB}
      - CLI_URL_LIBPIPELINE=${CLI_URL_LIBPIPELINE}

    command:
      - /${ENTRY_DIR}/${ENTRY_POINT}
